name = "playjonny-spiel-de"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=playjonny-spiel.de"
HMAC_KEY = "bbfa45dc1560bfde149d0a839eeff8178f83476ce376ceb05a7903d50c58fad3"
COOKIE_NAME = "g6k"
PLAY_PATH = "visit-site"
BUTTON_ID = "pd25dec0ed51bcc39f0e97602084a07fd"
GATE_SALT = "81c7b96d64d695e9"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "tlv9"
CTA_SELECTOR = ".play-button"
